
Create table REGISTER_USERS(sl_no int generated by default as identity primary key , 
name varchar(200) not null , 
email varchar(200) unique ,
password varchar(200)
);

Create table Contact(sl_no int generated by default as identity primary key , 
name varchar(200) not null , 
dob date ,
gender char(1) ,
created_Date date  
);

create table contact_emails(sl_no int generated by default as identity primary key ,
contact_sl int references contact(sl_no) on delete cascade ,
email varchar(100));

create table contact_tags(sl_no int generated by default as identity primary key ,
contact_sl int references contact(sl_no) on delete cascade ,
tag varchar(100));

create table contact_phoneNumbers(sl_no int generated by default as identity primary key ,
contact_sl int references contact(sl_no) on delete cascade ,
phoneNumber varchar(100));


insert into contact(name,dob,gender,created_date)values('nandu','2022-09-28','F','2022-05-13');

SELECT name,dob,gender,created_date,email,tag,phoneNumber
FROM contact
INNER JOIN 
contact_emails
ON contact.sl_no = contact_emails.contact_sl
INNER JOIN 
contact_tags
ON contact.sl_no = contact_tags.contact_sl
INNER JOIN 
contact_phoneNumbers
ON contact.sl_no = contact_phoneNumbers.contact_sl;


SELECT name,dob,gender,created_date,email,tag,phoneNumber
FROM (((contact
INNER JOIN 
contact_emails
ON contact.sl_no = contact_emails.contact_sl)
INNER JOIN 
contact_tags
ON contact.sl_no = contact_tags.contact_sl)
INNER JOIN 
contact_phoneNumbers
ON contact.sl_no = contact_phoneNumbers.contact_sl);


SELECT 
	* 
FROM 
	CONTACT
INNER JOIN
	CONTACT_EMAILS ON CONTACT.SL_NO=CONTACT_EMAILS.CONTACT_SL;


  parent
LEFT JOIN child1 AS c1 ON p.parent_id = c1.child_id
LEFT JOIN child2 AS c2 ON p.parent_id = c2.child_id

SELECT name,dob,gender,created_date,email,tag,phoneNumber
FROM contact
LEFT JOIN contact_emails ON contact.sl_no = contact_emails.contact_sl
LEFT JOIN contact_tags ON contact.sl_no = contact_tags.contact_sl
LEFT JOIN contact_tags ON contact.sl_no = contact_phoneNumbers.contact_sl;





SELECT 
 CONTACT.SL_NO AS c_sl,
 CONTACT.NAME AS c_name,
 CONTACT_EMAILS.EMAIL AS email 
FROM 
 CONTACT INNER JOIN CONTACT_EMAILS ON CONTACT.SL_NO=CONTACT_EMAILS.CONTACT_SL;
